name: HotkeyEvent
main: com.github.galaxyily.HotkeyEvent
description: Custom Hotkey Manager
author: galaxyily
version: 1.1
api-version: 1.16
depend: [ProtocolLib]
commands:
  hotkeyreload:
    description: Reload HotkeyManager config
    permission: hotkeymanager.reload
    usage: /hotkeyreload
